#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libyami-utils
Version  : 1.3.1
Release  : 4
URL      : https://github.com/intel/libyami-utils/archive/1.3.1.tar.gz
Source0  : https://github.com/intel/libyami-utils/archive/1.3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: libyami-utils-bin = %{version}-%{release}
Requires: libyami-utils-license = %{version}-%{release}
Requires: libyami-utils-man = %{version}-%{release}
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libva-wayland)
BuildRequires : pkgconfig(libva-x11)
BuildRequires : pkgconfig(libyami)
BuildRequires : pkgconfig(x11)

%description
Applications and Scripts for libyami.

%package bin
Summary: bin components for the libyami-utils package.
Group: Binaries
Requires: libyami-utils-license = %{version}-%{release}
Requires: libyami-utils-man = %{version}-%{release}

%description bin
bin components for the libyami-utils package.


%package license
Summary: license components for the libyami-utils package.
Group: Default

%description license
license components for the libyami-utils package.


%package man
Summary: man components for the libyami-utils package.
Group: Default

%description man
man components for the libyami-utils package.


%prep
%setup -q -n libyami-utils-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542230921
%autogen --disable-static --disable-avformat \
--disable-v4l2 \
--disable-md5 \
--enable-x11 \
--enable-dmabuf
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542230921
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libyami-utils
cp LICENSE %{buildroot}/usr/share/package-licenses/libyami-utils/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/grid
/usr/bin/psnr
/usr/bin/simpleplayer
/usr/bin/yamidecode
/usr/bin/yamiencode
/usr/bin/yamiinfo
/usr/bin/yamitranscode
/usr/bin/yamivpp

%files license
%defattr(-,root,root,-)
/usr/share/package-licenses/libyami-utils/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/yamidecode.1
/usr/share/man/man1/yamiencode.1
/usr/share/man/man1/yamiinfo.1
/usr/share/man/man1/yamitranscode.1
/usr/share/man/man1/yamivpp.1
