#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libyami-utils
Version  : 1.3.0
Release  : 2
URL      : https://github.com/intel/libyami-utils/archive/1.3.0.tar.gz
Source0  : https://github.com/intel/libyami-utils/archive/1.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: libyami-utils-bin
Requires: libyami-utils-doc
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libva-wayland)
BuildRequires : pkgconfig(libva-x11)
BuildRequires : pkgconfig(libyami)
BuildRequires : pkgconfig(x11)

%description
Applications and Scripts for libyami.

%package bin
Summary: bin components for the libyami-utils package.
Group: Binaries

%description bin
bin components for the libyami-utils package.


%package doc
Summary: doc components for the libyami-utils package.
Group: Documentation

%description doc
doc components for the libyami-utils package.


%prep
%setup -q -n libyami-utils-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526321666
%autogen --disable-static --disable-avformat \
--disable-v4l2 \
--disable-md5 \
--enable-x11 \
--enable-dmabuf
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1526321666
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/grid
/usr/bin/psnr
/usr/bin/simpleplayer
/usr/bin/yamidecode
/usr/bin/yamiencode
/usr/bin/yamiinfo
/usr/bin/yamitranscode
/usr/bin/yamivpp

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
